version: 2.1
orbs:
  poetry: frameio/poetry@0.15.0
executor:
  name: python
  tag: 3.8
workflows:
  ci:
    jobs:
      - poetry/build:
          cwd: ./saw-script/saw-remote-api/python/.
      - poetry/shell:
          args: pylint ./saw-script/saw-remote-api/python/.
          requires:
            - poetry/build
      - poetry/install:
          cwd: ./saw-script/saw-remote-api/python/.
          requires:
            - poetry/build
